---
- name: ansible trial
  hosts: all
  become: true
  vars:
    SITE_NAME: site-b
    TREES:
      - 'step 1'
      - 'step 2'
    MODE: ''
  tasks:
    - name: install EPEL repo
      yum:
        name: epel-release
        state: present

    - name: install Nginx
      yum:
        name: nginx
        state: present

    - name: start Nginx service
      service:
        name: nginx
        state: started
        enabled: true

    - name: create HTML contents directory
      file:
        path: "/usr/share/nginx/html/{{ item }}"
        state: directory
      with_items:
        - "site-a"
        - "site-b"

    - name: deploy Web contents for site-a
      copy:
        src: ./www/site-a/index.html
        dest: /usr/share/nginx/html/site-a/index.html

    - name: deploy Web contents for site-b with template
      template:
        src: ./www/site-b/index.html.j2
        dest: /usr/share/nginx/html/site-b/index.html

    - name: deploy Web contents for product page
      copy:
        src: ./www/site-a/product.html
        dest: /usr/share/nginx/html/site-a/product.html
      when:
        - MODE == 'product'

    - name: deploy Web contents for dev page
      copy:
        src: ./www/site-a/dev.html
        dest: /usr/share/nginx/html/site-a/dev.html
      when:
        - MODE == 'dev'

    - name: echo something
      command: echo "something"
      register: result

    - debug: var=result

    - name: do something by result
      command: echo "register"
      when: result.stdout == "something"
