---
- name: create HTML contents directory
  file:
    path: "/var/www/html/{{ item }}"
    state: directory
  with_items:
    - "site-a"
    - "site-b"

- name: deploy Web contents for site-a
  copy:
    src: site-a/index.html
    dest: /var/www/html/site-a/index.html

- name: deploy Web contents for site-b with template
  template:
    src: site-b/index.html.j2
    dest: /var/www/html/site-b/index.html

- name: deploy Web contents for product page
  copy:
    src: site-a/product.html
    dest: /var/www/html/site-a/product.html
  when:
    - MODE == 'product'

- name: deploy Web contents for dev page
  copy:
    src: site-a/dev.html
    dest: /var/www/html/site-a/dev.html
  when:
    - MODE == 'dev'

- name: echo something
  command: echo "something"
  register: result

- debug: var=result

- name: do something by result
  command: echo "register"
  when: result.stdout == "something"